services:
  sdk-api:
    build:
      context: .
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - SECRET_API_KEY=${SECRET_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - MONGODB_URL=${MONGODB_URL}
      - APP_PORT=${APP_PORT}
      - MODE=${MODE}
      - PROXY_URL=${PROXY_URL}