version: "3"

services:
  sdk-api:
    build:
      context: .
      secrets:
        - aws_access_key_id
        - aws_secret_access_key
    ports:
      - "3000:3000"

    
secrets:
  aws_access_key_id:
    environment: "AWS_ACCESS_KEY_ID"
  aws_secret_access_key:
    environment: "AWS_SECRET_ACCESS_KEY"