services:
  sdk-api:
    build:
      context: .
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "3000:3000"
    environment:
      - CLIENT_ID=${CEDE_CLIENT_ID}
      - SECRET_API_KEY=${CEDE_SECRET_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - PORT=3000
      - NODE_ENV=production

    
secrets:
  aws_access_key_id:
    environment: "AWS_ACCESS_KEY_ID"
  aws_secret_access_key:
    environment: "AWS_SECRET_ACCESS_KEY"